# Generated by Django 5.0.7 on 2024-07-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='cell_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='z',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
