# Generated by Django 5.0.7 on 2024-07-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_point_cell_position_point_file_name_alter_point_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='x',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='y',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='z',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
