# Generated by Django 5.0.7 on 2024-07-16 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_alter_point_x_alter_point_y_alter_point_z'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='point',
            name='file_name',
        ),
        migrations.AddField(
            model_name='point',
            name='point_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='points.pointfile'),
        ),
    ]
