# Generated by Django 5.0.7 on 2024-07-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_pointfile_remove_point_file_name_point_point_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='cell_position',
        ),
        migrations.AddField(
            model_name='point',
            name='column_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='row_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
